wzm/Controllers/DhcpServerLeasesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using tik4net;
using tik4net.Objects;
using tik4net.Objects.Ip;
using tik4net.Objects.Ip.DhcpServer;
using wzm.Extensions;
using wzm.Validations;
using wzmCore.Extensions;
using wzmCore.Interfaces;
using wzmData.Models;

namespace wzm.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DhcpServerLeasesController : Controller
    {

        ApplicationDbContext _db;
        ILogger<DhcpServerLeasesController> _loger;
        private readonly IWzmCore _wzmCore;

        public DhcpServerLeasesController(ApplicationDbContext db, IWzmCore wzmCore,ILogger<DhcpServerLeasesController> logger)
        {
            _db = db;

            _wzmCore = wzmCore;

            _loger = logger;
        }

        // GET: DhcpServerLeases
        public IActionResult Index()
        {
            if (!_db.ValidateMKCrendential().Validate)
            {
                TempData["errorCredenciales"] = _db.ValidateMKCrendential().Message;

                return Redirect("MikrotikCredentials");
            }

            IEnumerable<DhcpServerLease> d = _wzmCore.MikrotikManager.Ip.DhcpServer.GetServerLeases(_db.MikrotikCredentials.Include(c => c.Dispositivo).First(c => c.Selected == true)).ToList();

            return View(d.OrderBy(c => c.Status == "bound").ToList());


        }




        // GET: DhcpServerLeases/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null || id == string.Empty)
            {
                return NotFound();
            }
            var c = _db.MikrotikCredentials.Include(d => d.Dispositivo).FirstOrDefault(d => d.Selected);

            var l = _wzmCore.MikrotikManager.Ip.DhcpServer.GetLeaseById(c, id);
            return View(l);
        }

        // POST: DhcpServerLeases/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, [Bind("Address,LeaseTime,AlwaysBroadcast,MacAddress,Id,SrcMacAddress,ClientId,BlockAccess")]DhcpServerLease lease)
        {
            try
            {
                var c = _db.MikrotikCredentials.Include(d => d.Dispositivo).FirstOrDefault(d => d.Selected);
                var df = _wzmCore.MikrotikManager.Ip.DhcpServer.GetServerLeases(c);
                var vb = df.FirstOrDefault(h => h.Id == id);
                vb.Address = lease.Address;
                //if (lease.LeaseTime.Seconds == 0 & lease.LeaseTime.Minutes == 0 && lease.LeaseTime.Hours == 0)
                //{
                //    vb.LeaseTime = new TimeSpan(00, 00, 00);
                //}
                //else
                //{
                vb.LeaseTime = lease.LeaseTime;
                //}

                vb.AlwaysBroadcast = lease.AlwaysBroadcast;
                vb.MacAddress = lease.MacAddress;
                vb.SrcMacAddress = lease.SrcMacAddress;
                vb.BlockAccess = lease.BlockAccess;
                vb.ClientId = lease.ClientId;
                using (var connection = ConnectionFactory.OpenConnection(c.Dispositivo.Firmware.GetApiVersion(), c.Dispositivo.Ip, c.User, c.Password))
                {

                    connection.Save(vb);

                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception)
            {
                return View(lease);
            }
        }


        public IActionResult SaveToDatabase()
        {
            //var mikrotikCredential = _db.MikrotikCredentials.Include(c => c.Dispositivo).FirstOrDefault(c => c.Selected == true);

            //using (ITikConnection connection = ConnectionFactory.OpenConnection(TikConnectionType.Api, mikrotikCredential.Dispositivo.Ip, mikrotikCredential.User, mikrotikCredential.Password))
            //{
            //    IEnumerable<DhcpServerLease> d = _wzmCore.MikrotikManager.Ip.DhcpServer.GetServerLeases(connection).ToList();
            //    List<IpPool> ipPool = _wzmCore.MikrotikManager.Ip.Pool.GetIpPools(connection);
            //    List<IpDhcpServer> ipDhcpServers = (List<IpDhcpServer>)connection.LoadAll<IpDhcpServer>();
            //    DeleteFromDatabse();

            //    foreach (var item in ipPool)
            //    {
            //        _db.Add(item);
            //        _db.SaveChanges();
            //    }

            //    foreach (var item in ipDhcpServers)
            //    {
            //        _db.IpDhcpServers.Add(item);
            //        _db.SaveChanges();
            //    }

            //    foreach (var item in d)
            //    {
            //        _db.DhcpServerLease.Add(item);
            //        _db.SaveChanges();
            //    }
            //}


            return RedirectToAction(nameof(Index));
        }

        private void DeleteFromDatabse()
        {
            //var sl = _db.DhcpServerLease.ToList();
            //foreach (var item in sl)
            //{
            //    _db.Remove(item);
            //    _db.SaveChanges();
            //}

            //var dhcpservers = _db.IpDhcpServers.ToList();
            //foreach (var item in dhcpservers)
            //{
            //    _db.Remove(item);
            //    _db.SaveChanges();
            //}

            //var IpPools = _db.IpPools.ToList();
            //foreach (var item in IpPools)
            //{
            //    _db.Remove(item);
            //    _db.SaveChanges();
            //}
        }



        public IActionResult RestoreToDevice()
        {
            var cr = _db.MikrotikCredentials.Include(c => c.Dispositivo).First(c => c.Selected == true);

            using (ITikConnection connection = ConnectionFactory.OpenConnection(cr.Dispositivo.Firmware.GetApiVersion(), cr.Dispositivo.Ip, cr.User, cr.Password))
            {
                List<DhcpServerLease> d = _wzmCore.MikrotikManager.Ip.DhcpServer.GetServerLeases(cr).ToList();
                //var dhcpNetwork = _wzmCore.MikrotikManager.Ip.DhcpServer.GetDhcpServerNetworks(connection);
                DeleteFromDevice(d, cr);
                ImportToDevice(cr);
                d = _wzmCore.MikrotikManager.Ip.DhcpServer.GetServerLeases(cr).ToList();
            }


            return RedirectToAction(nameof(Index));
        }

        private void ImportToDevice(MikrotikCredentials cr)
        {
            //var l = _db.DhcpServerLease.ToList();
            //foreach (var item in l)
            //{
            //    try
            //    {
            //        _wzmCore.MikrotikManager.Ip.DhcpServer.AddLease(cr, item);
            //    }
            //    catch (Exception e)
            //    {
            //        _loger.LogCritical(e, "Error importando DHCP Server Lease");       
            //    }

            //}
        }

        /// <summary>
        /// Elimina los Lease del DhcpServer
        /// </summary>
        /// <param name="d"></param>
        /// <param name="cr"></param>
        private void DeleteFromDevice(List<DhcpServerLease> d, MikrotikCredentials cr)
        {
            if (d.Count > 0)
            {
                foreach (var item in d)
                {
                    _wzmCore.MikrotikManager.Ip.DhcpServer.DeleteLease(cr, item);
                }
            }
        }
    }
}

wzm/Views/DhcpServerLeases/Details.cshtml
@model wzmData.Models.MikrotikCredentials

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>MikrotikCredentials</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
   
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

wzm/Views/DhcpServerLeases/Edit.cshtml
@model tik4net.Objects.Ip.DhcpServer.DhcpServerLease
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-heading"></div>
<h4 class="ui top attached block header">
    Editar DHCP Lease: @Model.Comment
</h4>

<div class="ui bottom blue attached segment">
    <form asp-action="Edit">
        <div class="ui form">
            <div asp-validation-summary="All" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="two fields">
                <div class="field">
                    <label>Ip</label>
                    <input asp-for="Address" />
                    <span asp-validation-for="Address" class="field error"></span>
                </div>
                <div class="field">
                    <label>MAC</label>
                    <input asp-for="MacAddress" />
                    <span asp-validation-for="MacAddress" class="text-danger"></span>
                </div>
            </div>
            <div class="two fields">
                <div class="field">
                    <label asp-for="SrcMacAddress"></label>
                    <input asp-for="SrcMacAddress" />
                    <span asp-validation-for="SrcMacAddress" class="text-danger"></span>
                </div>

                <div class="field">
                    <label>Id del Cliente</label>
                    <input asp-for="ClientId" />
                    <span asp-validation-for="ClientId" class="text-danger"></span>
                </div>


            </div>

            <div class="equal width fields">
                <div class="field">
                    <label asp-for="LeaseTime"></label>
                    <input asp-for="LeaseTime" />
                    <span asp-validation-for="LeaseTime" class="text-danger"></span>
                </div>

            </div>

            <div class="fields">


                <div class="field">
                    <div class="ui checkbox">
                        <input type="checkbox" asp-for="AlwaysBroadcast">
                        <label asp-for="AlwaysBroadcast"></label>
                    </div>
                </div>

                <div class="field">
                    <div class="ui checkbox">
                        <input type="checkbox" asp-for="BlockAccess">
                        <label>Bloquear Acceso</label>
                    </div>
                </div>

            </div>

        </div>
        <div class="ui section divider"></div>
        <div class="ui buttons">
            <a asp-action="Index" class="ui red button">Cancelar</a>
            <div class="or" data-text="ó"></div>
            <button type="submit" class="ui primary button">Guardar</button>
        </div>

    </form>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    <script>
        $('.ui.checkbox')
            .checkbox();
    </script>

}

wzm/Views/DhcpServerLeases/Index.cshtml
@model IEnumerable<tik4net.Objects.Ip.DhcpServer.DhcpServerLease>
@using wzm.ViewComponents
@{
    ViewData["Title"] = "DhcpLeases";
}

@await Component.InvokeAsync(nameof(Messages))


@section styles{
    <link href="~/lib/DataTables/css/dataTables.semanticui.css" rel="stylesheet" />
    <link href="~/lib/DataTables/datatables.css" rel="stylesheet" />
}

<h2 class="ui header">
    DHCP Server Leases

</h2>
<form class="ui form">
    <div class="inline fields">
        <a asp-controller="DhcpServerLeases" asp-action="AllStatic" class="ui small primary button">Hacer todas estáticas</a>
        <button asp-action="SaveToDatabase" class="ui small green labeled icon button">
            <i class="save icon"></i> Hacer Salva
        </button>
        <button asp-action="RestoreToDevice" class="ui small red labeled icon button">
            <i class="restore icon"></i> Restaurar
        </button>
    </div>


    <table id="example" class="ui celled table" style="width:100%">
        <thead>
            <tr>
                <th>
                    Address
                </th>
                <th>
                    Mac Address
                </th>
                <th>
                    Active Address
                </th>
                <th>
                    Active Host Name
                </th>
                <th>
                    Estado
                </th>
                <th>Dinámica</th>
                <th>
                    Comentario
                </th>

                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                if (item.Status == "bound")
                {
                    <tr class="positive">
                        <td>
                            @item.Address
                        </td>
                        <td>
                            @item.MacAddress
                        </td>
                        <td>
                            @item.ActiveAddress
                        </td>
                        <td>
                            @item.HostName
                        </td>
                        <td>
                            @item.Status
                        </td>
                        <td>
                            @item.Dynamic
                        </td>
                        <td>
                            @item.Comment
                        </td>

                        @if (item.Dynamic)
                        {
                            <td>

                                <a asp-action="MakeStatic" data-tooltip="Detalles" class="ui green button" asp-route-id="@item.Id">Hacer Estática</a>
                            </td>
                        }
                        else
                        {
                            <td>

                                <a asp-action="Edit" data-tooltip="Editar" asp-route-id="@item.Id"><i class="green edit icon"></i></a>
                            </td>
                        }

                    </tr>
                }
                else
                {
                    <tr class="negative">
                        <td>
                            @item.Address
                        </td>
                        <td>
                            @item.MacAddress
                        </td>
                        <td>
                            @item.ActiveAddress
                        </td>
                        <td>
                            @item.HostName
                        </td>
                        <td>
                            @item.Status
                        </td>
                        <td>
                            @item.Dynamic
                        </td>
                        <td>
                            @item.Comment
                        </td>
                        @if (item.Dynamic)
                        {
                            <td>

                                <a asp-action="MakeStatic" data-tooltip="Detalles" class="ui green button" asp-route-id="@item.Id">Hacer Estática</a>
                            </td>
                        }
                        else
                        {
                            <td>

                                <a asp-action="Edit" data-tooltip="Editar" asp-route-id="@item.Id"><i class="green edit icon"></i></a>
                            </td>
                        }

                    </tr>
                }

            }
        </tbody>

    </table>

</form>

@section Scripts{
    <script src="~/lib/DataTables/js/dataTables.semanticui.js"></script>
    <script src="~/lib/DataTables/datatables.js"></script>

    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
}