wzm/Controllers/ConfConexPriorityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using tik4net;
using tik4net.Objects.Queue;
using wzm.Extensions;
using wzm.Validations;
using wzmCore.Interfaces;
using wzmCore.Mikrotik.Configuration;
using wzmData.Models;

namespace wzm.Controllers
{
    [Authorize(Roles = "Admin")]
    
    public class ConfConexPriorityController : Controller
    {
        ApplicationDbContext _db;

        private readonly IWzmCore _wzmCore;

        public ConfConexPriorityController(ApplicationDbContext db, IWzmCore wzmCore)
        {
            _db = db;
            _wzmCore = wzmCore;
        }

        // GET: ConfConexPriority
        public IActionResult Index()
        {
           
            if (!_db.ValidateMKCrendential().Validate)
            {
                TempData["errorCredenciales"] = _db.ValidateMKCrendential().Message;

                return Redirect("MikrotikCredentials");
            }


            var c = _db.MikrotikCredentials.Include(d => d.Dispositivo).FirstOrDefault(d => d.Selected);


            var qTree = _wzmCore.MikrotikManager.QueueTree.GetAllQueueTree(c);

            var qTrees = new List<QueueTree>();

            var parentsUpload = new List<QueueTree>();
            var parentsDownload = new List<QueueTree>();
            var parents = new List<QueueTree>();

            //Obtengo las interfaces
            var interfaces = _wzmCore.MikrotikManager.Interface.GetInterfaces(c);

            // Obtengo los parents de las interfaces
            foreach (var item in interfaces)
            {
                if (qTree.Any(d => d.Parent.Equals(item.Name)))
                {
                    parentsUpload.AddRange(qTree.Where(d => d.Parent.Equals(item.Name) && d.Queue.Equals("Subida")));
                    parentsDownload.AddRange(qTree.Where(d => d.Parent.Equals(item.Name) && d.Queue.Equals("Bajada")));
                }
            }

            foreach (var item in parentsUpload)
            {

                qTrees.AddRange(qTree.Where(d => d.Parent.Equals(item.Name)));
            }

            foreach (var item in parentsDownload)
            {
                qTrees.AddRange(qTree.Where(d => d.Parent.Equals(item.Name)));
            }

            if (parentsDownload.Count == parentsUpload.Count)
            {
                for (int i = 0; i < parentsDownload.Count; i++)
                {
                    parents.Add(parentsDownload[i]);
                    parents.Add(parentsUpload[i]);

                }
            }



            ViewData["Parents"] = parents;
            ViewData["QTrees"] = qTrees;

            return View();

        }

        public ActionResult Edit(string id)
        {
            var c = _db.MikrotikCredentials.Include(d => d.Dispositivo).FirstOrDefault(d => d.Selected);
            var qTree = _wzmCore.MikrotikManager.QueueTree.GetAllQueueTree(c);

            if (!qTree.Any(d => d.Id.Equals(id)))
            {
                return NotFound();
            }
            else
            {
                if (ModelState.IsValid)
                {

                }
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("id,MaxLimit,Priority,MaxLimit")] QueueTree queueTree)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            try
            {
                new QoS().DeleteQoSfromPortal(_db.MikrotikCredentials.Include(c => c.Dispositivo).FirstOrDefault(c => c.Selected), id.Split(' ')[0]);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewData["error"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public IActionResult ConfAutomatica()
        {
            var c = _db.MikrotikCredentials.Include(s => s.Dispositivo).FirstOrDefault(d => d.Selected);

            using (var connection = ConnectionFactory.OpenConnection(TikConnectionType.Api, c.Dispositivo.Ip, c.User, c.Password))
            {
                try
                {
                    _wzmCore.MikrotikManager.Firewall.Layer7.PriorityLayer7(c);
                    _wzmCore.MikrotikManager.QueueType.FirstConfig(c);
                    _wzmCore.MikrotikManager.Firewall.Mangle.PriorityMangle(c);
                    _wzmCore.MikrotikManager.QueueTree.FirstConfig(c);

                }
                catch (Exception e)
                {
                    TempData["error"] = e.Message;
                    return RedirectToAction(nameof(Index));
                }
                TempData["success"] = "La operación se ha realizado correctamente";
                return RedirectToAction(nameof(Index));
            }


        }
    }
}

wzm/Views/ConfConexPriority/Edit.cshtml
@model tik4net.Objects.Queue.QueueTree
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-heading"></div>
<h4 class="ui top attached block header">
    Editar
</h4>

<div class="ui bottom blue attached segment">
    <form asp-action="Edit" class="ui form">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />

        <div class="ui error message"></div>

        <div class="required field">
            <label>Prioridad</label>
            <input asp-for="Priority" name="Address" />
            <span asp-validation-for="Priority" class="text-red"></span>
        </div>
        <div class="required field">
            <label>Limitar en</label>
            <input asp-for="LimitAt" />
            <span asp-validation-for="LimitAt" class="text-danger"></span>
        </div>
        <div class="required field">
            <label>Límite Máximo</label>
            <input asp-for="MaxLimit" />
            <span asp-validation-for="MaxLimit" class="text-danger"></span>
        </div>




        <div class="ui section divider"></div>

        <div class="ui buttons">
            <a asp-action="Index" class="ui button">Cancelar</a>
            <div class="or" data-text="ó"></div>
            <button type="submit" class="ui positive button">Guardar</button>
        </div>
    </form>
</div>

<script>
    $('.ui.form')
        .form({
            fields: validationRules,
            inline: true,
            on: 'blur'
        })
        ;
</script>

wzm/Views/ConfConexPriority/Index.cshtml
@using wzm.ViewComponents
@using tik4net.Objects.Queue
@{
    ViewData["Title"] = "Optimizar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Component.InvokeAsync(nameof(Messages))

<h2 class="ui header">
    Calidad de Servicio
</h2>
<div class="inline fields">
    <div class="field">
    </div>
    <div class="field">
        <a asp-controller="ConfConexPriority" asp-action="ConfAutomatica" class="ui small negative labeled icon button">
            <i class="add configure icon"></i> Configuración Automática
        </a>

    </div>

</div>

<div class="ui divider"></div>
<div class="ui form">

    <table class="ui compact celled table">
        <thead>
            <tr>

                <th>Nombre</th>
                <th>Parent</th>
                <th>Packet Marks</th>
                <th>Limit At</th>
                <th>Max Limit</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Parents != null)
            {
                List<QueueTree> parents = (List<QueueTree>)ViewBag.Parents;
                List<QueueTree> qTree = (List<QueueTree>)ViewBag.qTrees;


                foreach (var item in parents)
                {
                    var itemParents = qTree.Where(c => c.Parent.Equals(item.Name));
                    <tr class="positive">
                        <td>
                            <i class="icon wi-fi"></i>
                            @item.Name

                        </td>
                        <td>@item.Parent</td>
                        <td>@item.PacketMark</td>
                        <td>@item.LimitAt</td>
                        <td>@item.MaxLimit</td>
                        <td> <a asp-action="Delete" data-tooltip="Eliminar QoS" asp-route-id="@item.Name"><i class="red small delete icon"></i></a></td>


                    </tr>
                    @foreach (var parent in itemParents)
                    {

                        var limitAt = (int.Parse(parent.LimitAt) / 1000);
                        var maxLimit = (int.Parse(parent.MaxLimit) / 1000);

                        <tr class="negative">
                            <td>@parent.Name</td>
                            <td>@parent.Parent</td>
                            <td>@parent.PacketMark</td>
                            <td>@limitAt K</td>

                            <td>@maxLimit K</td>
                            <td> <a asp-action="Eidt" data-tooltip="Editar" asp-route-id="@item.Id"><i class="blue small edit icon"></i></a></td>

                        </tr>
                    }



                }

            }

        </tbody>

    </table>
</div>